[package]
name = "openagro"
version = "0.1.0"
edition = "2021"
license = "lgpl-3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[profile.dev]
opt-level=3